//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.12.29 at 10:44:54 PM EET 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://album.nure.ua/entity", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package album.entity;
